import Logo from "./components/Logo"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <header>
        <Logo />
      </header>
      <main>
      {children}
      </main>
      </body>
    </html>
  )
}
