
import Logo from "./components/Logo"
import Navigation from "./components/Navigation"

export const metadata = {
  title: 'The Wild Oasis',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <header>
        <Logo />
        <Navigation />
      </header>
      <main>
      {children}
      </main>
      <footer>Copyright by The-Wild-Oasis @2025</footer>
      </body>
    </html>
  )
}
